- name: download netflow plugin
  get_url:
    url: https://github.com/Graylog2/graylog-plugin-netflow/releases/download/2.4.0-beta.2/graylog-plugin-netflow-2.4.0-beta.2.jar
    dest: /usr/share/graylog-server/plugin
  notify: restart graylog

